// The shared base: vocabulary, codecs, ABI, signatures and the pieces every layer below the Runtime reads.
// Generated by split/split.ts from the monolithic xln.ts. Imports point down: base <- account <- entity <- runtime.
import { secp256k1 } from "@noble/curves/secp256k1";
import { sha256 } from "@noble/hashes/sha2";
import { keccak_256 } from "@noble/hashes/sha3";
import { bytesToHex as nobleHex } from "@noble/hashes/utils";

// ---- vocabulary: brands, tagged unions, Result ----
declare const __brand: unique symbol;
export type Brand<T, B extends string> = T & { readonly [__brand]: { readonly [K in B]: B } };
export type Flat<T> = { readonly [K in keyof T]: T[K] } & {};
export type Tagged<Tag extends string, Extra extends object = {}> =
  Tag extends unknown ? Flat<{ readonly _tag: Tag } & Extra> : never;
export type Of<T extends { readonly _tag: string }, K extends T["_tag"]> =
  Extract<T, { readonly _tag: K }>;
/** A tagged value: the payload is required (`{}` for none) and cannot carry a `_tag` of its own. */
export const tag = <T extends string>(_tag: T) =>
  <X extends object & { readonly _tag?: never }>(x: X): Tagged<T, X> => ({ _tag, ...x }) as Tagged<T, X>;
/** `{k: v}` when defined, `{}` otherwise — absence and undefined are one value (§4.2). */
export const opt = <K extends string, V>(k: K, v: V | undefined): { readonly [P in K]?: V } =>
  (v === undefined ? {} : { [k]: v }) as { readonly [P in K]?: V };


export type Result<T, E> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: E };
export const ok = <T>(value: T): Result<T, never> => ({ ok: true, value });
export const err = <E>(error: E): Result<never, E> => ({ ok: false, error });
export const assertNever = (x: never): never => { throw new Error(`unreachable: ${String(x)}`); };
export const map = <T, U, E>(r: Result<T, E>, f: (t: T) => U): Result<U, E> =>
  (r.ok ? ok(f(r.value)) : r);
export const chain = <T, U, E, F>(r: Result<T, E>, f: (t: T) => Result<U, F>): Result<U, E | F> =>
  (r.ok ? f(r.value) : r);
export const mapErr = <T, E, F>(r: Result<T, E>, f: (e: E) => F): Result<T, F> =>
  (r.ok ? r : err(f(r.error)));
export const guard = <E>(pass: boolean, e: E): Result<void, E> => (pass ? ok(undefined) : err(e));
export const unwrapOr = <T, E>(r: Result<T, E>, f: (e: E) => T): T => (r.ok ? r.value : f(r.error));
/** Snapshots the iterable, then folds left to right; the first refusal is the answer and `f` sees no later item. */
export const foldResult = <S, X, E>(
  xs: Iterable<X>, init: S, f: (s: S, x: X, i: number) => Result<S, E>,
): Result<S, E> =>
  [...xs].reduce<Result<S, E>>((acc, x, i) => (acc.ok ? f(acc.value, x, i) : acc), ok(init));
/**
 * Folds left to right and collects one output per item; the first refusal is the answer.
 *
 * The one transient accumulator in the vocabulary (listed in style/README.md). Appending with
 * `[...ys, y]` copied every earlier output on every step, so each fold over n items cost n²
 * (review B1: 2.7 s at n = 40k). `collected` is created by this call, only this call pushes to it,
 * and it is handed out once, after the last push, as a readonly array no caller shares.
 * mapAccum, traverse, strictFold and lenientFold all fold through here.
 */
export const mapAccumResult = <S, X, Y, E>(
  xs: Iterable<X>, init: S, f: (s: S, x: X, i: number) => Result<readonly [S, Y], E>,
): Result<readonly [S, readonly Y[]], E> => {
  const collected: Y[] = [];
  const keep = ([next, y]: readonly [S, Y]): S => {
    collected.push(y);
    return next;
  };
  const stepOnce = (s: S, x: X, i: number): Result<S, E> => map(f(s, x, i), keep);
  return map(foldResult(xs, init, stepOnce), (last) => [last, collected] as const);
};
export const mapAccum = <S, X, Y>(
  xs: Iterable<X>, init: S, f: (s: S, x: X, i: number) => readonly [S, Y],
): readonly [S, readonly Y[]] =>
  unwrapOr(mapAccumResult(xs, init, (s, x, i) => ok(f(s, x, i))), assertNever);
export const traverse = <X, Y, E>(
  xs: Iterable<X>, f: (x: X, i: number) => Result<Y, E>,
): Result<readonly Y[], E> => {
  const collect = (_: undefined, x: X, i: number) => map(f(x, i), (y) => [undefined, y] as const);
  return map(mapAccumResult(xs, undefined, collect), ([, ys]) => ys);
};
/** First refusal among eagerly evaluated checks, in order. */
export const checks = <E>(...rs: readonly Result<unknown, E>[]): Result<void, E> =>
  foldResult(rs, undefined as void, (_, r) => map(r, () => undefined));
type Values<R> = { readonly [K in keyof R]: R[K] extends Result<infer V, unknown> ? V : never };
type Errors<R> = R[keyof R] extends Result<unknown, infer E> ? E : never;
export const all = <R extends Record<string, Result<unknown, unknown>>>(
  cs: R,
): Result<Values<R>, Errors<R>> => {
  // Collects [key, value] pairs and builds the record once; spreading the record per key was n².
  const collect = ([k, r]: readonly [string, unknown]) =>
    map(r as Result<unknown, Errors<R>>, (v) => [k, v] as const);
  return map(traverse(Object.entries(cs), collect), Object.fromEntries) as Result<Values<R>, Errors<R>>;
};
/** The first answer among lazily asked questions; later questions are never asked once one answers. */
export const firstDefined = <T>(...asks: readonly (() => T | undefined)[]): T | undefined =>
  asks.reduce<T | undefined>((found, ask) => found ?? ask(), undefined);
/** A refusable step over a value that may be absent; absence passes through as absence. */
export const whenDefined = <T, U, E>(v: T | undefined, f: (t: T) => Result<U, E>): Result<U | undefined, E> =>
  v === undefined ? ok(undefined) : f(v);
/** `every` over a refusable predicate: the first `false` or the first refusal ends it; later items are not asked. */
export const everyResult = <X, E>(xs: Iterable<X>, pass: (x: X) => Result<boolean, E>): Result<boolean, E> =>
  foldResult(xs, true, (all, x) => (all ? pass(x) : ok(false)));
/** `some` over a refusable predicate: the first `true` or the first refusal ends it; later items are not asked. */
export const someResult = <X, E>(xs: Iterable<X>, pass: (x: X) => Result<boolean, E>): Result<boolean, E> =>
  foldResult(xs, false, (any, x) => (any ? ok(true) : pass(x)));

// ---- matching: exhaustive tables keyed by a discriminant ----
export const arm = <A extends object, K extends keyof A>(arms: A, k: K): A[K] =>
  (Object.hasOwn(arms, k) ? arms[k] : assertNever(k as never));
export const matchBy = <Key extends string, T extends Record<Key, PropertyKey>, R>(
  key: Key, value: T, arms: { [K in T[Key]]: (v: Extract<T, Record<Key, K>>) => R },
): R => arm(arms, value[key] as T[Key])(value as never);
export const match = <T extends { readonly _tag: string }, R>(
  value: T, arms: { [K in T["_tag"]]: (v: Of<T, K>) => R },
): R => matchBy("_tag", value, arms);
export const total = <K extends string, F>(names: readonly K[], f: F): { readonly [P in K]: F } =>
  Object.fromEntries(names.map((n) => [n, f])) as { readonly [P in K]: F };
export type Kinds<K extends string, Row> = { readonly [T in K]: Row };

// ---- replica grammars: which phase an event may move a replica to ----
type Table = { readonly [event: string]: { readonly [phase: string]: readonly string[] } };
export type Grammar = Readonly<{
  table: Table; replica: Tagged<string>; input: { readonly kind: string };
  ctx: { readonly [e: string]: unknown }; output: unknown; error: unknown;
}>;
export type Phase<G extends Grammar> = G["replica"]["_tag"];
export type Event<G extends Grammar> = keyof G["table"] & string;
export type At<G extends Grammar, P extends string> = Of<G["replica"], P>;
export type InputFor<G extends Grammar, E extends string> = Extract<G["input"], { readonly kind: E }>;
export type Next<G extends Grammar, P extends Phase<G>, E extends Event<G>> =
  P extends keyof G["table"][E] ? Extract<G["table"][E][P], readonly Phase<G>[]>[number] : never;
export type Apply<R, O> = { readonly replica: R; readonly outputs: readonly O[] };
export type Handler<G extends Grammar, E extends Event<G>, P extends Phase<G>> = (
  replica: At<G, P>, input: InputFor<G, E>, ctx: G["ctx"][E],
) => Result<Apply<At<G, Next<G, P, E>>, G["output"]>, G["error"]>;
/** A phase the table allows gets a handler; a phase it forbids gets the refusal to return. */
export type Cases<G extends Grammar, E extends Event<G>> = {
  readonly [P in Phase<G>]: P extends keyof G["table"][E] ? Handler<G, E, P> : G["error"];
};
export const grammar = <G extends Grammar>(_table: G["table"]) =>
  <E extends Event<G>, C extends Cases<G, E>>(_event: E, cases: C) =>
    (
      replica: G["replica"], input: InputFor<G, E>, ctx: G["ctx"][E],
    ): Result<Apply<G["replica"], G["output"]>, G["error"]> => {
      const branch = arm(cases, replica._tag as keyof C) as unknown;
      return typeof branch === "function" ? branch(replica, input, ctx) : err(branch as G["error"]);
    };
export const done = <R, O>(replica: R, outputs: readonly O[] = []): Apply<R, O> =>
  ({ replica, outputs });

const everyPhaseStays = {
  open: ["open"], proposed: ["proposed"], received: ["received"], preparing: ["preparing"],
  disputed: ["disputed"],
} as const;
const everyPhaseDisputes = {
  open: ["disputed"], proposed: ["disputed"], received: ["disputed"], preparing: ["disputed"],
  disputed: ["disputed"],
} as const;
export const AccountTransition = {
  propose: { open: ["open", "proposed"] },
  ack: {
    open: ["open"], proposed: ["open", "proposed"], received: ["open", "received"],
    preparing: ["preparing"], disputed: ["disputed"],
  },
  ack_frame: {
    open: ["open", "received"], proposed: ["open", "proposed", "received"], received: ["received"],
    preparing: ["preparing"], disputed: ["disputed"],
  },
  freeze: {
    open: ["preparing", "disputed"], proposed: ["preparing", "disputed"],
    received: ["preparing", "disputed"], preparing: ["preparing", "disputed"],
    disputed: ["disputed"],
  },
  dispute: everyPhaseStays,
  board_hanko_refresh: everyPhaseStays,
  resume: { preparing: ["open"] },
  external_finality: everyPhaseDisputes,
} as const;
export const EntityTransition = {
  txs: { open: ["open", "proposed"], proposed: ["open", "proposed"], locked: ["open", "locked"] },
  proposal: {
    open: ["open", "locked"], proposed: ["open", "proposed"], locked: ["open", "locked"],
  },
  precommit: { open: ["open"], proposed: ["open", "proposed"], locked: ["open", "locked"] },
  leaderTimeoutVote: {
    open: ["open", "proposed", "locked"], proposed: ["open", "proposed"],
    locked: ["open", "proposed", "locked"],
  },
  jPrefixAttestations: {
    open: ["open", "proposed"], proposed: ["open", "proposed"], locked: ["open", "locked"],
  },
} as const;

// ---- layers: one step of a state machine, folded strictly or leniently ----
export type Step<S, Eff> = { readonly state: S; readonly effects: readonly Eff[] };
export const step = <S, Eff = never>(state: S, effects: readonly Eff[] = []): Step<S, Eff> =>
  ({ state, effects });
export type Layer<S, X, C, Eff, E> = (s: S, x: X, c: C) => Result<Step<S, Eff>, E>;
/** Strict fold: one refusal refuses the frame. */
export const strictFold = <S, X, C, Eff, E>(apply: Layer<S, X, C, Eff, E>) =>
  (s: S, xs: Iterable<X>, c: C): Result<Step<S, Eff>, E> => {
    const applyOne = (cur: S, x: X) =>
      map(apply(cur, x, c), (r) => [r.state, r.effects] as const);
    return map(mapAccumResult(xs, s, applyOne), ([state, effects]) => step(state, effects.flat()));
  };
export type Lenient<S, X, Eff, E> = Step<S, Eff> & {
  readonly included: readonly X[];
  readonly refused: readonly { readonly index: number; readonly error: E }[];
};
type LenientItem<X, Eff, E> =
  | { readonly _tag: "folded"; readonly x: X; readonly effects: readonly Eff[] }
  | { readonly _tag: "refused"; readonly index: number; readonly error: E };
/** Lenient fold: a refused item is skipped, the rest go on. */
export const lenientFold = <S, X, C, Eff, E>(apply: Layer<S, X, C, Eff, E>) =>
  (s: S, xs: Iterable<X>, c: C): Lenient<S, X, Eff, E> => {
    const applyOne = (cur: S, x: X, index: number): readonly [S, LenientItem<X, Eff, E>] => {
      const r = apply(cur, x, c);
      return r.ok
        ? [r.value.state, tag("folded")({ x, effects: r.value.effects })]
        : [cur, tag("refused")({ index, error: r.error })];
    };
    const [state, items] = mapAccum(xs, s, applyOne);
    const folded = items.flatMap((item) => (item._tag === "folded" ? [item] : []));
    const refused = items.flatMap((item) => (item._tag === "refused" ? [item] : []));
    return {
      state, effects: folded.flatMap((f) => f.effects), included: folded.map((f) => f.x),
      refused: refused.map(({ index, error }) => ({ index, error })),
    };
  };

// ---- immutable collections ----
/** A new map with k set to v; the old map is unchanged. Copies m, so a fold that inserts wants mapSetAll. */
export const mapSet = <K, V>(m: ReadonlyMap<K, V>, k: K, v: V): ReadonlyMap<K, V> =>
  new Map([...m, [k, v]]);
/**
 * Every entry set in order, exactly as repeated mapSet would (a later entry wins, an existing key
 * keeps its place), but m is copied once: n inserts cost n, not n² as a fold over mapSet does.
 */
export const mapSetAll = <K, V>(m: ReadonlyMap<K, V>, entries: Iterable<readonly [K, V]>): ReadonlyMap<K, V> =>
  new Map([...m, ...entries]);
export const mapDelete = <K, V>(m: ReadonlyMap<K, V>, k: K): ReadonlyMap<K, V> =>
  new Map([...m].filter(([key]) => key !== k));
/** Adds d to the count at k; a count that reaches zero leaves the map. */
export const bump = <K>(m: ReadonlyMap<K, bigint>, k: K, d: bigint): ReadonlyMap<K, bigint> => {
  const v = (m.get(k) ?? 0n) + d;
  return v === 0n ? mapDelete(m, k) : mapSet(m, k, v);
};
/** Keeps the first item for each key, drops keys already taken; keyless items always stay. */
export const firstBy = <X, K>(
  xs: Iterable<X>, key: (x: X) => K | undefined, taken: Iterable<K> = [],
): readonly X[] => {
  const items = [...xs];
  const keys = items.map(key);
  const blocked = new Set(taken);
  const firstAt = new Map(keys.map((k, i) => [k, i] as const).toReversed());
  const kept = (i: number): boolean => {
    const k = keys[i];
    return k === undefined || (!blocked.has(k) && firstAt.get(k) === i);
  };
  return items.filter((_, i) => kept(i));
};

// ---- canonical text: the deterministic spelling every hash in the rewrite is taken over ----
export const asc = <T extends string | number | bigint>(a: T, b: T): number => (a < b ? -1 : a > b ? 1 : 0);
export const desc = <T extends string | number | bigint>(a: T, b: T): number => asc(b, a);
const sortedBy = <X>(xs: readonly X[], key: (x: X) => string): readonly X[] =>
  xs.map((x) => [key(x), x] as const).toSorted(([a], [b]) => asc(a, b)).map(([, x]) => x);
const sortWith = <X>(xs: Iterable<X>, cmp: (a: X, b: X) => number): readonly X[] =>
  [...xs].toSorted(cmp);
/** A lowercase 0x-prefixed 32-byte word: og's canonical spelling of a hash or an Entity id. */
const WORD32 = /^0x[0-9a-f]{64}$/;
/** A lowercase 0x-prefixed 20-byte address. */
const EOA = /^0x[0-9a-f]{40}$/;
/** og's three spellings of an id as text: any falsy value is blank in the first two, only nullish in the third. */
const lowerText = (v: unknown): string => String(v || "").toLowerCase();
const lower = (v: unknown): string => String(v || "").trim().toLowerCase();
const trimLower = (v: unknown): string => String(v ?? "").trim().toLowerCase();
const lengthPrefixed = (kind: string, body: string): string => `${kind}${body.length}:${body}`;
const countOf = (n: number): string => lengthPrefixed("d", String(n));
const canonMap = (m: ReadonlyMap<unknown, unknown>): string => {
  const rows = sortedBy([...m].map(([k, v]) => [canon(k), v] as const), ([k]) => k);
  return `m${countOf(rows.length)}${rows.map(([k, v]) => k + canon(v)).join("")}`;
};
const canonSet = (s: ReadonlySet<unknown>): string => {
  const rows = [...s].map(canon).toSorted(asc);
  return `S${countOf(rows.length)}${rows.join("")}`;
};
/** Undefined fields are absent, so `{a: undefined}` and `{}` spell the same. */
const canonObject = (o: Record<string, unknown>): string => {
  const keys = Object.keys(o).filter((k) => o[k] !== undefined).toSorted();
  return `o${countOf(keys.length)}${keys.map((k) => lengthPrefixed("s", k) + canon(o[k])).join("")}`;
};
/** Every value gets a type letter and a length, so no two different values share a spelling. */
export const canon = (v: unknown): string => {
  switch (true) {
    case v === undefined: return "u";
    case v === null: return "n";
    case typeof v === "boolean": return v ? "T" : "F";
    case typeof v === "bigint": return lengthPrefixed("i", v.toString());
    case typeof v === "string": return lengthPrefixed("s", v);
    case typeof v === "number": return lengthPrefixed("d", String(v));
    case v instanceof Map: return canonMap(v);
    case Array.isArray(v): return `a${countOf(v.length)}${v.map(canon).join("")}`;
    case v instanceof Set: return canonSet(v);
    case v instanceof Uint8Array: return lengthPrefixed("b", nobleHex(v));
    case typeof v === "object": return canonObject(v as Record<string, unknown>);
    default: return "u";
  }
};

// ---- hex, words and bytes ----
const nibble = (code: number): number => {
  const lower = code | 32;
  switch (true) {
    case code >= 48 && code <= 57: return code - 48;
    case lower >= 97 && lower <= 102: return lower - 87;
    default: return -1;
  }
};
export const hexBody = (h: string): string => (/^0[xX]/.test(h) ? h.slice(2) : h);
export const hexToBytes = (hex: string): Uint8Array => {
  const body = hexBody(hex);
  if (body.length % 2 !== 0) throw new Error(`odd hex length ${body.length}`);
  const byteAt = (_: unknown, i: number): number => {
    const hi = nibble(body.charCodeAt(2 * i));
    const lo = nibble(body.charCodeAt(2 * i + 1));
    if (hi < 0 || lo < 0) throw new Error(`bad hex at ${i}`);
    return (hi << 4) | lo;
  };
  return Uint8Array.from({ length: body.length / 2 }, byteAt);
};
export const bytesToHex = (b: Uint8Array): string => `0x${nobleHex(b)}`;
export const parseHex = (h: string): Uint8Array | null => {
  const body = hexBody(h);
  return body.length % 2 === 0 && /^[0-9a-fA-F]*$/.test(body) ? hexToBytes(h) : null;
};
export const joinHex = (parts: readonly string[]): string => `0x${parts.map(hexBody).join("")}`;
export const concat = (parts: readonly Uint8Array[]): Uint8Array => {
  const [size, starts] = mapAccum(parts, 0, (offset, p) => [offset + p.length, offset] as const);
  const joined = new Uint8Array(size);
  parts.forEach((p, i) => joined.set(p, starts[i]));
  return joined;
};
export const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s);
export const keccak256 = (b: Uint8Array): Uint8Array => keccak_256(b);
export const keccak256Hex = (b: Uint8Array): string => bytesToHex(keccak256(b));
export const wordOf = (n: bigint): Uint8Array => {
  if (n < 0n || n >= 1n << 256n) throw new Error("uint256 out of range");
  return hexToBytes(n.toString(16).padStart(64, "0"));
};
const INT256_MIN = -(1n << 255n), INT256_MAX = (1n << 255n) - 1n;
/** Two's complement: a negative n is written as 2^256 + n. */
export const wordOfSigned = (n: bigint): Uint8Array => {
  if (n < INT256_MIN || n > INT256_MAX) throw new Error("int256 out of range");
  return wordOf(n < 0n ? (1n << 256n) + n : n);
};
/** The 32-byte word at `at`; bytes past the end of the buffer read as zero. */
export const wordAt = (buf: Uint8Array, at: number): bigint =>
  BigInt(bytesToHex(Uint8Array.from({ length: 32 }, (_, i) => buf[at + i] ?? 0)));
const sized = (n: number) => (hex: string): Uint8Array => {
  const b = hexToBytes(hex);
  if (b.length !== n) throw new Error(`${n}-byte value is ${b.length} bytes`);
  return b;
};
const addressBytes = sized(20);
export const bytes32 = sized(32);
export const addressWord = (a: string): Uint8Array => concat([new Uint8Array(12), addressBytes(a)]);
const uint32Bytes = (n: number): Uint8Array => {
  if (!Number.isInteger(n) || n < 0 || n > 0xffff_ffff) throw new Error("uint32 out of range");
  return Uint8Array.of(n >>> 24, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff);
};

// ---- Solidity ABI: encoding, and typed cursors for decoding ----
export type Abi =
  | Tagged<"uint" | "int", { value: bigint }>
  | Tagged<"bool", { value: boolean }>
  | Tagged<"address" | "bytes32" | "bytes", { value: string }>
  | Tagged<"array" | "tuple", { value: readonly Abi[] }>;
export const A = {
  uint: (value: bigint): Abi => ({ _tag: "uint", value }),
  int: (value: bigint): Abi => ({ _tag: "int", value }),
  bool: (value: boolean): Abi => ({ _tag: "bool", value }),
  address: (value: string): Abi => ({ _tag: "address", value }),
  b32: (value: string): Abi => ({ _tag: "bytes32", value }),
  bytes: (value: string): Abi => ({ _tag: "bytes", value }),
  array: (value: readonly Abi[]): Abi => ({ _tag: "array", value }),
  tuple: (value: readonly Abi[]): Abi => ({ _tag: "tuple", value }),
} as const;
const arr = <X>(xs: readonly X[], f: (x: X) => Abi): Abi => A.array(xs.map((x) => f(x)));
const dynamic = (v: Abi): boolean => {
  switch (v._tag) {
    case "bytes": case "array": return true;
    case "tuple": return v.value.some(dynamic);
    default: return false;
  }
};
const padRight = (b: Uint8Array): Uint8Array => {
  const padding = Math.ceil(b.length / 32) * 32 - b.length;
  return padding === 0 ? b : concat([b, new Uint8Array(padding)]);
};
const uintWordHex = (n: bigint): string => nobleHex(wordOf(n));
const encodeValue = (v: Abi): string => match(v, {
  uint: (x) => uintWordHex(x.value),
  int: (x) => nobleHex(wordOfSigned(x.value)),
  bool: (x) => uintWordHex(x.value ? 1n : 0n),
  address: (x) => nobleHex(addressWord(x.value)),
  bytes32: (x) => nobleHex(bytes32(x.value)),
  bytes: (x) => {
    const b = hexToBytes(x.value);
    return uintWordHex(BigInt(b.length)) + nobleHex(padRight(b));
  },
  array: (x) => uintWordHex(BigInt(x.value.length)) + encodeSequence(x.value),
  tuple: (x) => encodeSequence(x.value),
});
/** Static values sit in the head; a dynamic value sits in the tail and its head holds the offset. */
const encodeSequence = (vs: readonly Abi[]): string => {
  const parts = vs.map((v) => ({ dynamic: dynamic(v), hex: encodeValue(v) }));
  const headSize = parts.reduce((n, p) => n + (p.dynamic ? 32 : p.hex.length / 2), 0);
  const [, heads] = mapAccum(parts, headSize, (tailAt, p) => p.dynamic
    ? [tailAt + p.hex.length / 2, uintWordHex(BigInt(tailAt))] as const
    : [tailAt, p.hex] as const);
  const tails = parts.filter((p) => p.dynamic).map((p) => p.hex);
  return [...heads, ...tails].join("");
};
export const abiEncodeHex = (vs: readonly Abi[]): string => `0x${encodeSequence(vs)}`;
export const abiEncode = (vs: readonly Abi[]): Uint8Array => hexToBytes(abiEncodeHex(vs));
export type Packed =
  | Tagged<"uint256", { value: bigint }>
  | Tagged<"uint32", { value: number }>
  | Tagged<"bool", { value: boolean }>
  | Tagged<"address" | "bytes32" | "bytes", { value: string }>;
const packedBytes = (p: Packed): Uint8Array => match(p, {
  uint256: (x) => wordOf(x.value), uint32: (x) => uint32Bytes(x.value),
  bool: (x) => Uint8Array.of(x.value ? 1 : 0), address: (x) => addressBytes(x.value),
  bytes32: (x) => bytes32(x.value), bytes: (x) => hexToBytes(x.value),
});
export const encodePacked = (parts: readonly Packed[]): Uint8Array => concat(parts.map(packedBytes));

/** A cursor at the head of a tuple. */
export type AbiTuple = Brand<number, "AbiTuple">;
/** A cursor at the length word of a dynamic array or byte string. */
export type AbiLength = Brand<number, "AbiLength">;
const T = (n: number): AbiTuple => n as AbiTuple, L = (n: number): AbiLength => n as AbiLength;
const itemAt = (l: AbiLength, i: number): number => l + 32 + i * 32;
export const abiRoot = (): AbiTuple => T(0);
export const abiCursorOk = (h: AbiTuple): boolean => Number.isFinite(h) && h >= 0;
export const abiTupleRef = (buf: Uint8Array, h: AbiTuple, slot: number): AbiTuple =>
  T(h + Number(wordAt(buf, h + slot)));
export const abiLengthRef = (buf: Uint8Array, h: AbiTuple, slot: number): AbiLength =>
  L(h + Number(wordAt(buf, h + slot)));
export const abiWord = (buf: Uint8Array, h: AbiTuple, slot: number): bigint => wordAt(buf, h + slot);
export const abiTupleBytes = (buf: Uint8Array, h: AbiTuple, slot: number): Uint8Array =>
  buf.subarray(h + slot, h + slot + 32);
export const abiLengthWord = (buf: Uint8Array, l: AbiLength): bigint => wordAt(buf, l);
export const abiBytes = (buf: Uint8Array, l: AbiLength): Uint8Array =>
  buf.subarray(l + 32, l + 32 + Number(wordAt(buf, l)));
/** Whether `count` items of `stride` bytes fit after the length word; none always fit. */
export const abiFits = (buf: Uint8Array, l: AbiLength, count: bigint, stride: number): boolean => {
  if (!Number.isFinite(l) || l < 0) return false;
  const start = l + 32;
  return start > buf.length ? count === 0n : count * BigInt(stride) <= BigInt(buf.length - start);
};
export const abiBytesElement = (buf: Uint8Array, l: AbiLength, i: number): AbiLength =>
  L(l + 32 + Number(wordAt(buf, itemAt(l, i))));
export const abiTupleElement = (buf: Uint8Array, l: AbiLength, i: number): AbiTuple =>
  T(l + 32 + Number(wordAt(buf, itemAt(l, i))));
export const abiInlineTuple = (l: AbiLength, i: number, stride: number): AbiTuple =>
  T(l + 32 + i * stride);
export const abiStaticWord = (buf: Uint8Array, l: AbiLength, i: number): bigint =>
  wordAt(buf, itemAt(l, i));
export const abiStaticBytes = (buf: Uint8Array, l: AbiLength, i: number): Uint8Array =>
  buf.subarray(itemAt(l, i), itemAt(l, i) + 32);

// ---- signatures and identities ----
export type RawSignature = Readonly<{
  r: bigint; s: bigint; recovery: number; publicKey: Uint8Array;
}>;
export const signRaw = (h: Uint8Array, privateKey: Uint8Array): RawSignature => {
  const s = secp256k1.sign(h, privateKey, { prehash: false, lowS: true });
  const publicKey = s.recoverPublicKey(h).toRawBytes(false);
  return { r: s.r, s: s.s, recovery: s.recovery, publicKey };
};
export const recoverPublicKey = (
  h: Uint8Array, r: Uint8Array, s: Uint8Array, bit: number,
): Uint8Array | null => {
  try {
    const signature = secp256k1.Signature.fromCompact(concat([r, s])).addRecoveryBit(bit);
    return signature.recoverPublicKey(h).toRawBytes(false);
  } catch {
    return null;
  }
};
export type EntityId = Brand<string, "EntityId">;
export type TokenId = Brand<string, "TokenId">;
export type Address = Brand<string, "Address">;
export type Hash = Brand<string, "Hash">;
export type Signature = Brand<string, "Signature">;
export type RuntimeFrameHash = Brand<Hash, "RuntimeFrameHash">;
export type EntityStateHash = Brand<Hash, "EntityStateHash">;
export type EntityFrameHash = Brand<Hash, "EntityFrameHash">;
export type AccountId = Brand<{ readonly left: EntityId; readonly right: EntityId }, "AccountId">;
/** Separator characters are refused because ids are joined into composite keys. */
const branded = <T extends string, E extends string>(s: string, e: E): Result<T, E> =>
  (s.length === 0 || /[|;=,]/.test(s) ? err(e) : ok(s as T));
export const entityId = (s: string): Result<EntityId, "invalid_entity_id"> =>
  branded(s, "invalid_entity_id");
export const address = (s: string): Result<Address, "invalid_address"> =>
  branded(s, "invalid_address");
export const tokenId = (s: unknown): Result<TokenId, "invalid_token_id"> => {
  const isUint16Text = typeof s === "string" && /^(0|[1-9][0-9]{0,4})$/.test(s) && Number(s) <= 65_535;
  return isUint16Text ? ok(s as TokenId) : err("invalid_token_id");
};
export const hash = (s: string): Result<Hash, "invalid_hash"> =>
  (/^[0-9a-f]{64}$/.test(s) ? ok(s as Hash) : err("invalid_hash"));
export const signature = (s: string): Result<Signature, "invalid_signature"> => {
  const evenHex = /^[0-9a-f]+$/.test(s) && s.length >= 2 && s.length % 2 === 0;
  return evenHex && !/^0+$/.test(s) ? ok(s as Signature) : err("invalid_signature");
};
export const ZERO_HASH = "0".repeat(64) as Hash;
export const ZERO_WORD = `0x${ZERO_HASH}`;
export const WORD = /^0x[0-9a-fA-F]{64}$/;
export const keccakUtf8 = (s: string): Hash => nobleHex(keccak_256(utf8(s))) as Hash;
export const sameHex = (a: string | undefined, b: string | undefined): boolean =>
  a !== undefined && b !== undefined && a.toLowerCase() === b.toLowerCase();
/** Lowercase, and pad a short hex word to 32 bytes. Equal-length hex then compares as an integer. */
const normalizeId = (id: string): string => {
  const raw = id.toLowerCase();
  const hex = raw.slice(2);
  const shortHexWord = raw.startsWith("0x") && /^[0-9a-f]*$/.test(hex) && hex.length < 64;
  return shortHexWord ? `0x${hex.padStart(64, "0")}` : raw;
};
const before = (a: string, b: string): boolean => normalizeId(a) < normalizeId(b);
const sameId = (a: string, b: string): boolean => normalizeId(a) === normalizeId(b);
/** The lower id is always the left side, so both parties name the Account the same way. */
export const accountId = (a: EntityId, b: EntityId): Result<AccountId, Tagged<"same_entity">> => {
  if (sameId(a, b)) return err({ _tag: "same_entity" });
  const sides = before(a, b) ? { left: a, right: b } : { left: b, right: a };
  return ok(sides as AccountId);
};
export const isLeft = (party: EntityId, id: AccountId): boolean => party === id.left;
export const at = <T>(left: T, right: T, onLeft: boolean): T => (onLeft ? left : right);
export const other = (onLeft: boolean): boolean => !onLeft;
export type Party = { readonly self: EntityId; readonly peer: EntityId; readonly left: boolean };
export const counterpartyOf = (id: AccountId, self: EntityId): EntityId | undefined => {
  switch (self) {
    case id.left: return id.right;
    case id.right: return id.left;
    default: return undefined;
  }
};
export const partyOf = (
  id: AccountId, self: EntityId,
): Result<Party, Tagged<"unknown_signer", { entity: EntityId }>> => {
  const peer = counterpartyOf(id, self);
  if (peer === undefined) return err({ _tag: "unknown_signer", entity: self });
  return ok({ self, peer, left: isLeft(self, id) });
};
/** Whoever holds a proposed frame proposed it; whoever holds a received frame did not. */
export const proposerIsLeft = (
  held: { readonly _tag: "proposed" | "received" }, party: Party,
): boolean => (held._tag === "proposed" ? party.left : other(party.left));

// ---- canonical value encoding: RLP over typed nodes, and the flat integrity digest ----
export type CanonicalValueError = Tagged<"non_finite_number" | "unsupported_type" | "invalid_utf8">;
type Rlp = Uint8Array | readonly Rlp[];
const magnitude = (v: bigint): Uint8Array => {
  const h = v.toString(16);
  return hexToBytes(h.length % 2 === 0 ? h : `0${h}`);
};
/** RLP's three spellings: a lone low byte is itself, a short body gets one prefix, a long one its length. */
const payload = (body: Uint8Array, list: boolean): Uint8Array => {
  const loneLowByte = !list && body.length === 1 && (body[0] ?? 0x80) < 0x80;
  if (loneLowByte) return body;
  if (body.length <= 55) return concat([Uint8Array.of((list ? 0xc0 : 0x80) + body.length), body]);
  const size = magnitude(BigInt(body.length));
  return concat([Uint8Array.of((list ? 0xf7 : 0xb7) + size.length), size, body]);
};
const rlp = (n: Rlp): Uint8Array =>
  (n instanceof Uint8Array ? payload(n, false) : payload(concat(n.map(rlp)), true));
const LONE_SURROGATE = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/;
const text = (v: string): Result<Uint8Array, CanonicalValueError> =>
  (LONE_SURROGATE.test(v) ? err({ _tag: "invalid_utf8" }) : ok(utf8(v)));
const labelled = (label: string, ...rest: readonly Rlp[]): Rlp => [utf8(label), ...rest];
const numberNode = (v: number): Result<Rlp, CanonicalValueError> =>
  (Number.isFinite(v) ? ok(labelled("number", utf8(String(v)))) : err({ _tag: "non_finite_number" }));
const bigintNode = (v: bigint): Rlp =>
  labelled("bigint", Uint8Array.of(v < 0n ? 1 : 0), magnitude(v < 0n ? -v : v));
const mapNode = (m: ReadonlyMap<unknown, unknown>): Result<Rlp, CanonicalValueError> => {
  const rows = traverse(m, ([k, v]) => traverse([k, v], cnode));
  const byKey = (row: readonly Rlp[]): string => bytesToHex(rlp(row[0] ?? []));
  return map(rows, (rs) => labelled("map", ...sortedBy(rs, byKey)));
};
const setNode = (s: ReadonlySet<unknown>): Result<Rlp, CanonicalValueError> =>
  map(traverse(s, cnode), (ns) => labelled("set", ...sortedBy(ns, (n) => bytesToHex(rlp(n)))));
const objectNode = (o: Record<string, unknown>): Result<Rlp, CanonicalValueError> => {
  const keys = Object.keys(o).toSorted(asc).filter((k) => o[k] !== undefined);
  const field = (k: string) => chain(text(k), (name) => map(cnode(o[k]), (n): Rlp => [name, n]));
  return map(traverse(keys, field), (fields) => labelled("object", ...fields));
};
const cnode = (v: unknown): Result<Rlp, CanonicalValueError> => {
  switch (true) {
    case v === null: return ok(labelled("null"));
    case typeof v === "boolean": return ok(labelled("bool", Uint8Array.of(v ? 1 : 0)));
    case typeof v === "number": return numberNode(v);
    case typeof v === "bigint": return ok(bigintNode(v));
    case typeof v === "string": return map(text(v), (b) => labelled("string", b));
    case Array.isArray(v): return map(traverse(v, cnode), (ns) => labelled("array", ...ns));
    case v instanceof Map: return mapNode(v);
    case v instanceof Set: return setNode(v);
    case typeof v === "object": return objectNode(v as Record<string, unknown>);
    default: return err({ _tag: "unsupported_type" });
  }
};
export const encodeCanonicalValue = (v: unknown): Result<Uint8Array, CanonicalValueError> =>
  map(cnode(v), rlp);
/** og state-root.ts:133-161: the frame hash and the state commitment both use this, under two namespaces. */
export const flatDigest = (
  namespace: string, sections: readonly (readonly [string, unknown])[],
): Result<string, CanonicalValueError> => {
  const leafOf = ([path, value]: readonly [string, unknown]) => map(encodeCanonicalValue(value), (enc) => {
    const key = sha256(utf8(`xln.${namespace}.${path}`));
    return { key, hex: bytesToHex(key), digest: sha256(enc) };
  });
  return map(traverse(sections, leafOf), (leaves) => {
    const ordered = sortedBy(leaves, (l) => l.hex).flatMap((l) => [l.key, l.digest]);
    return bytesToHex(sha256(concat([utf8("xln.flat-digest.v1"), ...ordered])));
  });
};

// Used by the layers above.
export {
  EOA, INT256_MAX, INT256_MIN, LONE_SURROGATE, WORD32, arr, before, lower, lowerText, magnitude, rlp, sameId, sortWith,
  sortedBy, trimLower,
};
export type { Rlp };
